### ISSUE TITLE
SystemJS tries to load ng2-slider.component.html.js

### ISSUE THREAD

**Issue by robertkardos** [Bogdan1975/ng2-slider-component#10]
After setting the ng2-slider component up in SystemJS:
`var map = {
    ...
    'ng2-slider-component': 'node_modules/ng2-slider-component',
    'ng2-slideable-directive': 'node_modules/ng2-slideable-directive',
    'ng2-styled-directive': 'node_modules/ng2-styled-directive',
    ...
};`

`var packages = {
    ...
    'ng2-slider-component': { main: 'ng2-slider.component.js'},
    'ng2-slideable-directive': { main: 'slideable.directive.js'},
    'ng2-styled-directive': { main: 'ng2-styled.directive.js'},
    ...
};`

and trying to import it in one of my components:
`import * as slider from 'ng2-slider-component';`

I get the following error on the console log:

**http://localhost:4000/node_modules/ng2-slider-component/ng2-slider.component.html.js**

It seems I can't set any sort of exceptional rule for .html files in SystemJS to load them without .js extension.

How did you get it working? Am I missing something?

**Comment by Bogdan1975** [comment]
Im publish new version with SystemJS compatible files to npm

*.js files compiled for WebPack

If you use SystemJS, you have to use `*.system.js` files, they are compiled for SystemJS.

Fragment of SystemJS config:

``` javascript
packages: {

    ....

    'node_modules/ng2-slider-component': {
            main: 'ng2-slider.component.system.js',
            defaultExtension: 'system.js' 
    },

    .... 

}
```
