### ISSUE TITLE
most of the sliders on demo page don't work

### ISSUE THREAD

**Issue by chadbr** [Bogdan1975/ng2-slider-component#2]
http://www.jqueryrain.com/?HcwhMsRg

These don't seem to be working (range slider handles pop to the top of the page?)

**Comment by Bogdan1975** [comment]
Hi.
Can't recreate this problem.
Crome: http://i.prntscr.com/59a2a13bbbb94d2e866ee7c9c4724b9d.png
FireFox: http://i.prntscr.com/d12e2558d51243748173b0437d0b1bf9.png
Opera: http://i.prntscr.com/4d6e16e31c764e7aa94f494b700054a9.png

What browser do U use?

**Comment by chadbr** [comment]
OSX Chrome...  They all show fine initially, but the "buttons" go into random places when you interact with them (usually to the top of the page...)
<img width="677" alt="screen shot 2016-07-05 at 9 53 30 am" src="https://cloud.githubusercontent.com/assets/3179452/16588890/98029848-4296-11e6-82ae-930c899885da.png">

**Comment by davidTurczi** [comment]
I can totally confirm that, on Windows, Chrome.

**Comment by me-12** [comment]
Same here on Chrome -> Windows

**Comment by DanielleJobeJKI** [comment]
can confirm on chrome & mac that I see this, too

**Comment by Bogdan1975** [comment]
So. Realy problem is present. It is not problem of this component, it's problem with slideable-directive.
I want to make it very flexible but in fact this affects the complexity. Maybe I'll be forced to rewrite 70% of slideable-directive.
I hope, durin July I'll solve this problem.
P.S. Thank your all for issue, it's important for me

**Comment by davidTurczi** [comment]
I need a pure angular2 slider rather asap. Anything I can help?

**Comment by Bogdan1975** [comment]
> I need a pure angular2 slider rather asap. Anything I can help?

I think tomorrow updated version will be commited

**Comment by Bogdan1975** [comment]
New version was commited.
Works, but have some bugs when scroll directly during the sliding.

**Comment by kidtronnix** [comment]
I think I have a similar issue, whenever i click on the slider button it jumps to the right.
