### ISSUE TITLE
Slider is not showing only input field for the value

### ISSUE THREAD

**Issue by medin-n** [Bogdan1975/ng2-slider-component#25]
After successful importing, slider is not showing only the input field for number.

**Comment by frozenL** [comment]
similar issue

**Comment by medin-n** [comment]
So i find out that the css is not loaded properly.
I fix this by coping the css and pasting to my css then it works ):

**Comment by sajeetharan** [comment]
how did you fix this?

**Comment by ShakurOo** [comment]
Same here, i'll definitively remove this poor "component".

**Comment by arunbjain** [comment]
@Usamedid - where did you get the css?

**Comment by rach12345** [comment]
I am facing the same issue. Slider is not visible, but only 2 input fields are present. I see that there is no css.
@usamedin which CSS did you load?

**Comment by medin-n** [comment]
I just give up on this component because i face with so many issues, instead i start using https://github.com/tb/ng2-nouislider
much better library.

**Comment by rach12345** [comment]
Yes. I too found it. But with ng2-nouislider, I get **'nouiSlider (9.2.0): Start is required'** error.
Did you face it? And how did you resolve it?

**Comment by medin-n** [comment]
Aha yes that you need to have model attached to the component in the .ts create model like 
range=[2,10]; 
In html 
       <nouislider  [(ngModel)]="range" ></nouislider>
and other required variables as well

**Comment by rach12345** [comment]
Can you please elaborate a little more?
Because I have used ngModel along with the nouislider component.
I have raised this issue in the following thread:
**https://github.com/tb/ng2-nouislider/issues/48**
