### ISSUE TITLE
Source code included in the npm package

### ISSUE THREAD

**Issue by davidTurczi** [Bogdan1975/ng2-slider-component#3]
Hi,
you've included both the .d.ts and the .ts in the npm packages, so when I import your module, the implementation is pulled in and recompiled. And since I use stricter compilation options (like implicitAny:false) it is not compiling for me. If you take a look at angular2's npm packages, you'll see they only include the .d.ts and the .js files (plus whatever metadata they need).

**Comment by SebastianStehle** [comment]
Also need a fix here :(

**Comment by kjartanvalur** [comment]
Please include the source files.. "Cannot find source file 'ng2-slider.component.ts':"

**Comment by Bogdan1975** [comment]
ng2-slider.component.ts exist in repository, it is not included in npm package only

**Comment by dumparun** [comment]
Hello @Bogdan1975 ... Understand that the TS file is in repo, this shows a lot of warnings in CLI and console which is not a good practice to go for production release. There is no harm in releasing the source in NPM, if so would it be possible for you to do the same and update please
