### ISSUE TITLE
Feature request: ValueChanged after release

### ISSUE THREAD

**Issue by SebastianStehle** [Bogdan1975/ng2-slider-component#4]
Hi,

I like what you have done so far. I would like to have an event that triggers when the user releases the mouse.

**Comment by Bogdan1975** [comment]
"onRangeChanged" event triggers when user releases the mouse button

**Comment by SebastianStehle** [comment]
Right, you should fix the demo ;)

**Comment by Bogdan1975** [comment]
What wrong in demo now?

**Comment by SebastianStehle** [comment]
The Value labels are not updated.

**Comment by Bogdan1975** [comment]
Oh. Realy. I'll fix it today some later
Thank U.

**Comment by Bogdan1975** [comment]
Fixed
